-- ROI Monitoring Module
-- Tracks value generated by Gilbertus/Omnius across domains:
-- builder (system development), management (delegation/decisions),
-- life (personal), operational (user-level automation)

BEGIN;

-- Organizational hierarchy: owner > company > department > team > user
CREATE TABLE IF NOT EXISTS roi_hierarchy (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('owner', 'company', 'department', 'team', 'user')),
    parent_id BIGINT REFERENCES roi_hierarchy(id) ON DELETE SET NULL,
    hourly_rate_pln NUMERIC(10, 2) DEFAULT 0,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_roi_hierarchy_parent ON roi_hierarchy(parent_id);
CREATE INDEX IF NOT EXISTS idx_roi_hierarchy_type ON roi_hierarchy(type);

-- Individual value-generating activities
CREATE TABLE IF NOT EXISTS roi_activities (
    id BIGSERIAL PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES roi_hierarchy(id) ON DELETE CASCADE,
    activity_type TEXT NOT NULL,
    domain TEXT NOT NULL CHECK (domain IN ('builder', 'management', 'life', 'operational')),
    value_pln NUMERIC(12, 2) DEFAULT 0,
    time_saved_min INTEGER DEFAULT 0,
    description TEXT,
    source_table TEXT,
    source_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_roi_activities_entity ON roi_activities(entity_id);
CREATE INDEX IF NOT EXISTS idx_roi_activities_domain ON roi_activities(domain);
CREATE INDEX IF NOT EXISTS idx_roi_activities_created ON roi_activities(created_at);
CREATE INDEX IF NOT EXISTS idx_roi_activities_source ON roi_activities(source_table, source_id);

-- Period summaries per hierarchy node and domain
CREATE TABLE IF NOT EXISTS roi_summaries (
    id BIGSERIAL PRIMARY KEY,
    entity_id BIGINT NOT NULL REFERENCES roi_hierarchy(id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    domain TEXT,
    total_value_pln NUMERIC(14, 2) DEFAULT 0,
    synergy_bonus_pln NUMERIC(14, 2) DEFAULT 0,
    breakdown JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(entity_id, period_start, period_end, domain)
);

CREATE INDEX IF NOT EXISTS idx_roi_summaries_entity ON roi_summaries(entity_id);
CREATE INDEX IF NOT EXISTS idx_roi_summaries_period ON roi_summaries(period_start, period_end);

-- Seed: Sebastian as owner, REH and REF as companies
INSERT INTO roi_hierarchy (name, type, parent_id, hourly_rate_pln, metadata)
VALUES ('Sebastian Jabłoński', 'owner', NULL, 600, '{"role": "owner", "domains": ["builder", "management", "life"]}')
ON CONFLICT DO NOTHING;

INSERT INTO roi_hierarchy (name, type, parent_id, hourly_rate_pln, metadata)
SELECT 'REH (Respect Energy Holding)', 'company', h.id, 0, '{"domain": "operational"}'
FROM roi_hierarchy h WHERE h.name = 'Sebastian Jabłoński' AND h.type = 'owner'
AND NOT EXISTS (SELECT 1 FROM roi_hierarchy WHERE name = 'REH (Respect Energy Holding)');

INSERT INTO roi_hierarchy (name, type, parent_id, hourly_rate_pln, metadata)
SELECT 'REF (Respect Energy Fuels)', 'company', h.id, 0, '{"domain": "operational"}'
FROM roi_hierarchy h WHERE h.name = 'Sebastian Jabłoński' AND h.type = 'owner'
AND NOT EXISTS (SELECT 1 FROM roi_hierarchy WHERE name = 'REF (Respect Energy Fuels)');

COMMIT;
