#!/usr/bin/env bash
# Gilbertus One-Click Install & Launch
# Usage:
#   bash scripts/setup.sh              # production (Docker)
#   bash scripts/setup.sh --dev        # local dev mode
#   bash scripts/setup.sh --no-browser # skip opening browser
#
# Exit codes: 0 success, 1 missing prereqs, 2 build failed, 3 health check failed
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

OPEN_BROWSER=true
DEV_MODE=false

for arg in "$@"; do
    case "$arg" in
        --no-browser) OPEN_BROWSER=false ;;
        --dev)        DEV_MODE=true ;;
        -h|--help)
            echo "Usage: bash scripts/setup.sh [--dev] [--no-browser]"
            echo "  --dev         Use local dev mode (pnpm dev + docker-compose.yml)"
            echo "  --no-browser  Skip opening browser after setup"
            exit 0
            ;;
    esac
done

# ── Colors ────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; }

# ── 1. Check prerequisites ───────────────────────────────────────────
info "Checking prerequisites..."

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        fail "$1 is not installed."
        return 1
    fi
    ok "$1 found: $(command -v "$1")"
    return 0
}

MISSING=false

if ! check_cmd docker; then
    echo "  Install Docker: https://docs.docker.com/get-docker/"
    MISSING=true
fi

if ! docker compose version &>/dev/null 2>&1; then
    fail "docker compose (v2 plugin) not found."
    echo "  Install: https://docs.docker.com/compose/install/"
    MISSING=true
else
    ok "docker compose found"
fi

if ! check_cmd git; then
    echo "  Install git: https://git-scm.com/downloads"
    MISSING=true
fi

if [ "$DEV_MODE" = true ]; then
    if ! check_cmd node; then
        echo "  Install Node.js 20+: https://nodejs.org/"
        MISSING=true
    fi
    if ! command -v pnpm &>/dev/null; then
        warn "pnpm not found, will try to enable via corepack"
        if command -v corepack &>/dev/null; then
            corepack enable && corepack prepare pnpm@latest --activate
            ok "pnpm enabled via corepack"
        else
            fail "Neither pnpm nor corepack found."
            echo "  Install pnpm: npm install -g pnpm"
            MISSING=true
        fi
    else
        ok "pnpm found"
    fi
fi

if [ "$MISSING" = true ]; then
    fail "Missing prerequisites. Install them and re-run."
    exit 1
fi

ok "All prerequisites met."

# ── 2. Generate .env if not exists ────────────────────────────────────
if [ -f "$PROJECT_DIR/.env" ]; then
    ok "Using existing .env"
else
    info "Generating .env from .env.example..."

    if [ ! -f "$PROJECT_DIR/.env.example" ]; then
        fail ".env.example not found in $PROJECT_DIR"
        exit 2
    fi

    cp "$PROJECT_DIR/.env.example" "$PROJECT_DIR/.env"

    # Generate secrets
    NEXTAUTH_SECRET=$(openssl rand -hex 32)
    POSTGRES_PW=$(openssl rand -hex 16)

    # Detect domain
    DOMAIN="${GILBERTUS_DOMAIN:-gilbertus.localhost}"

    # Append frontend/infra vars
    cat >> "$PROJECT_DIR/.env" <<EOF

# === Generated by setup.sh ($(date -Iseconds)) ===
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
GILBERTUS_URL=https://${DOMAIN}
GILBERTUS_DOMAIN=${DOMAIN}
EOF

    # Set Postgres password (replace placeholder)
    if grep -q 'POSTGRES_PASSWORD=REPLACE_ME' "$PROJECT_DIR/.env"; then
        sed -i "s/POSTGRES_PASSWORD=REPLACE_ME/POSTGRES_PASSWORD=${POSTGRES_PW}/" "$PROJECT_DIR/.env"
    fi

    ok ".env generated. Domain: ${DOMAIN}"

    # Check for required API keys
    NEEDS_KEYS=false
    for KEY in ANTHROPIC_API_KEY OPENAI_API_KEY; do
        if grep -q "${KEY}=.*REPLACE_ME" "$PROJECT_DIR/.env" || grep -q "${KEY}=$" "$PROJECT_DIR/.env"; then
            NEEDS_KEYS=true
        fi
    done

    if [ "$NEEDS_KEYS" = true ]; then
        warn "Review .env and add your API keys (ANTHROPIC_API_KEY, OPENAI_API_KEY, etc.)"
        warn "The app will start but AI features will not work without them."
    fi
fi

# ── 3. Build & Start ─────────────────────────────────────────────────
if [ "$DEV_MODE" = true ]; then
    # Dev mode: infrastructure via docker-compose.yml, frontend via pnpm
    info "Starting infrastructure (postgres, qdrant, whisper)..."
    docker compose -f docker-compose.yml up -d || { fail "Docker infrastructure failed."; exit 2; }

    info "Installing frontend dependencies..."
    cd "$PROJECT_DIR/frontend"
    pnpm install || { fail "pnpm install failed."; exit 2; }

    info "Starting frontend dev server..."
    pnpm dev &
    FRONTEND_PID=$!

    info "Starting backend API..."
    cd "$PROJECT_DIR"
    if [ -f "$PROJECT_DIR/venv/bin/activate" ]; then
        source "$PROJECT_DIR/venv/bin/activate"
    fi
    uvicorn app.api.main:app --host 127.0.0.1 --port 8000 --reload &
    API_PID=$!

    APP_URL="http://localhost:3000"

    # Trap to clean up background processes
    trap "kill $FRONTEND_PID $API_PID 2>/dev/null; docker compose -f docker-compose.yml down" EXIT

    info "Waiting for services..."
    sleep 5

else
    # Production mode: everything via Docker
    info "Building and starting all services..."

    COMPOSE_CMD="docker compose -f docker-compose.prod.yml"

    # Check if user wants SSL
    if [ "${GILBERTUS_SSL:-false}" = "true" ] || [ "${1:-}" = "--ssl" ]; then
        COMPOSE_CMD="$COMPOSE_CMD --profile with-ssl"
    fi

    $COMPOSE_CMD up -d --build 2>&1 || { fail "Docker build/start failed."; exit 2; }

    ok "Containers started."

    # Determine app URL
    DOMAIN="${GILBERTUS_DOMAIN:-gilbertus.localhost}"
    if docker compose -f docker-compose.prod.yml ps caddy 2>/dev/null | grep -q "running"; then
        APP_URL="https://${DOMAIN}"
    else
        APP_URL="http://localhost:3000"
    fi
fi

# ── 4. Wait for health checks ────────────────────────────────────────
info "Waiting for services to become healthy..."

wait_for_service() {
    local name="$1"
    local check_cmd="$2"
    local max_attempts="${3:-30}"
    local attempt=0

    printf "  Waiting for %-12s " "$name..."
    while [ $attempt -lt $max_attempts ]; do
        if eval "$check_cmd" &>/dev/null 2>&1; then
            echo -e "${GREEN}OK${NC}"
            return 0
        fi
        attempt=$((attempt + 1))
        sleep 2
    done
    echo -e "${RED}TIMEOUT${NC}"
    return 1
}

HEALTH_FAILED=false

if [ "$DEV_MODE" = false ]; then
    wait_for_service "postgres" "docker exec gilbertus-postgres pg_isready -U gilbertus" 30 || HEALTH_FAILED=true
    wait_for_service "api" "curl -sf http://localhost:8000/health" 30 || HEALTH_FAILED=true
    wait_for_service "web" "curl -sf http://localhost:3000" 30 || HEALTH_FAILED=true

    if docker compose -f docker-compose.prod.yml ps caddy 2>/dev/null | grep -q "running"; then
        wait_for_service "caddy" "curl -sf -k https://localhost/health" 15 || warn "Caddy not responding (SSL may need DNS setup)"
    fi
else
    wait_for_service "postgres" "docker exec gilbertus-postgres pg_isready -U gilbertus 2>/dev/null || pg_isready -h localhost -U gilbertus" 20 || HEALTH_FAILED=true
    wait_for_service "api" "curl -sf http://localhost:8000/health" 20 || HEALTH_FAILED=true
    wait_for_service "web" "curl -sf http://localhost:3000" 20 || HEALTH_FAILED=true
fi

if [ "$HEALTH_FAILED" = true ]; then
    fail "Some services failed health checks. Check logs:"
    echo "  docker compose -f docker-compose.prod.yml logs --tail=50"
    exit 3
fi

ok "All services healthy."

# ── 5. Run DB migrations if needed ───────────────────────────────────
if [ -f "$PROJECT_DIR/scripts/run_migrations.sh" ]; then
    info "Running DB migrations..."
    bash "$PROJECT_DIR/scripts/run_migrations.sh" 2>&1 || warn "Migrations had warnings (may already be applied)."
    ok "Migrations done."
fi

# ── 6. Print success ─────────────────────────────────────────────────
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Gilbertus is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  Frontend:  ${BLUE}${APP_URL}${NC}"
echo -e "  API:       ${BLUE}http://localhost:8000${NC}"
echo -e "  API docs:  ${BLUE}http://localhost:8000/docs${NC}"
echo ""
echo -e "  Login at ${BLUE}${APP_URL}/login${NC} with your API key."
echo ""

# ── 7. Open browser ──────────────────────────────────────────────────
if [ "$OPEN_BROWSER" = true ]; then
    open_url() {
        if command -v xdg-open &>/dev/null; then
            xdg-open "$1" 2>/dev/null &
        elif command -v open &>/dev/null; then
            open "$1" 2>/dev/null &
        elif command -v start &>/dev/null; then
            start "$1" 2>/dev/null &
        else
            info "Open in your browser: $1"
        fi
    }
    open_url "$APP_URL"
fi

# In dev mode, wait for background processes
if [ "$DEV_MODE" = true ]; then
    info "Dev mode running. Press Ctrl+C to stop."
    wait
fi

exit 0
