// Generated by orval — run `pnpm generate:api` to regenerate

import { customFetch } from './base';
import type { HealthResponse } from './types';

/**
 * Validates an API key by calling GET /health with it.
 * Returns true if the key is valid (200 response), false otherwise.
 */
export async function validateApiKey(key: string): Promise<boolean> {
  try {
    await customFetch<HealthResponse>({
      url: '/health',
      method: 'GET',
      headers: { 'X-API-Key': key },
    });
    return true;
  } catch {
    return false;
  }
}
